# Site settings
title: Colorincidence
email: colorincidences@gmail.com
description: Spontaneous Color Coincidences in the Urban Landscape
baseurl: ""
url: "https://colorincidences.github.io"
github_username: colorincidences

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  photos:
    output: true
    permalink: /photos/:name/
